#!/usr/bin/env python3
import json
import os

# HF_SPACES data from models.py
hf_spaces = {
    'coqui/xtts': {
        'name': 'XTTS v2',
        'function': '/predict',
        'text_param_index': 0,
        'return_audio_index': 0,
        'series': 'XTTS',
        'emoji': '😩',
        'title': 'Gradio version too old',
    },
    'collabora/WhisperSpeech': {
        'name': 'WhisperSpeech',
        'function': '/whisper_speech_demo',
        'text_param_index': 0,
        'return_audio_index': 0,
        'series': 'WhisperSpeech',
        'emoji': '😷',
        'title': 'Broken space - runtime error',
    },
    'myshell-ai/OpenVoice': {
        'name': 'OpenVoice',
        'function': '1',
        'text_param_index': 0,
        'return_audio_index': 1,
        'series': 'OpenVoice',
        'emoji': '😩',
        'title': 'Gradio version too old',
    },
    'myshell-ai/OpenVoiceV2': {
        'name': 'OpenVoice v2',
        'function': '1',
        'text_param_index': 0,
        'return_audio_index': 1,
        'series': 'OpenVoice',
        'emoji': '😩',
        'title': 'Gradio version too old',
    },
    'mrfakename/MetaVoice-1B-v0.1': {
        'name': 'MetaVoice',
        'function': '/tts',
        'text_param_index': 0,
        'return_audio_index': 0,
        'series': 'MetaVoice',
        'emoji': '😷',
        'title': 'Broken space - runtime error',
    },
    'Pendrokar/xVASynth-TTS': {
        'name': 'xVASynth v3 DeepMoji',
        'function': '/predict',
        'text_param_index': 0,
        'return_audio_index': 0,
        'series': 'xVASynth',
        'title': 'Outclassed',
    },
    'Pendrokar/xVASynth-TTS/NoDeepMoji': {
        'name': 'xVASynth v3',
        'function': '/predict',
        'text_param_index': 0,
        'return_audio_index': 0,
        'series': 'xVASynth',
        'space_link': 'Pendrokar/xVASynth-TTS',
        'title': 'Outclassed',
    },
    'coqui/CoquiTTS': {
        'name': 'CoquiTTS',
        'function': '0',
        'text_param_index': 0,
        'return_audio_index': 0,
        'series': 'CoquiTTS',
        'title': 'Outclassed',
    },
    'LeeSangHoon/HierSpeech_TTS': {
        'name': 'HierSpeech++',
        'function': '/predict',
        'text_param_index': 0,
        'return_audio_index': 0,
        'series': 'HierSpeech++',
        'emoji': '😒',
        'title': 'Narration voice',
    },
    'mrfakename/MeloTTS': {
        'name': 'MeloTTS',
        'function': '/synthesize',
        'text_param_index': 'text',
        'return_audio_index': 0,
        'series': 'MeloTTS',
        'emoji': '😷',
        'title': 'Broken space / Outclassed narration voice',
    },
    'parler-tts/parler_tts': {
        'name': 'Parler Mini',
        'function': '/gen_tts',
        'text_param_index': 0,
        'return_audio_index': 0,
        'is_zero_gpu_space': True,
        'series': 'Parler',
        'emoji': '😷',
        'title': 'Broken space - runtime error',
    },
    'parler-tts/parler_tts/large': {
        'name': 'Parler Large',
        'function': '/gen_tts',
        'text_param_index': 0,
        'return_audio_index': 0,
        'is_zero_gpu_space': True,
        'series': 'Parler',
        'emoji': '😷',
        'title': 'Broken space - runtime error',
        'space_link': 'parler-tts/parler_tts',
    },
    'parler-tts/parler-tts-expresso': {
        'name': 'Parler Mini Expresso',
        'function': '/gen_tts',
        'text_param_index': 0,
        'return_audio_index': 0,
        'is_zero_gpu_space': True,
        'series': 'Parler',
        'emoji': '😷',
        'title': 'Broken space - runtime error',
    },
    'PHBJT/multi_parler_tts': {
        'name': 'Parler Mini Multi v1.1',
        'function': '/gen_tts',
        'text_param_index': 'text',
        'return_audio_index': 1,
        'is_zero_gpu_space': True,
        'series': 'Parler',
        'title': 'Unstable',
    },
    'PHBJT/multi_parler_tts/reformatted': {
        'name': 'Parler Mini Multi v1.1r',
        'function': '/gen_tts',
        'text_param_index': 'text',
        'return_audio_index': 1,
        'is_zero_gpu_space': True,
        'series': 'Parler',
        'title': 'Unstable',
    },
    'innoai/Edge-TTS-Text-to-Speech': {
        'name': 'Microsoft® Edge TTS',
        'function': '/predict',
        'text_param_index': 0,
        'return_audio_index': 0,
        'is_closed_source': True,
        'series': 'Edge TTS',
        'emoji': '',
        'space_link': 'innoai/Edge-TTS-Text-to-Speech',
    },
    'fishaudio/fish-speech-1': {
        'name': 'Fish Speech',
        'function': '/inference_wrapper',
        'text_param_index': 'text',
        'return_audio_index': 0,
        'series': 'Fish Speech',
        'emoji': '😵',
        'title': 'Deprecated: Redirects to OpenAudio',
    },
    'fishaudio/openaudio-s1-mini': {
        'name': 'OpenAudio S1 Mini',
        'function': '/partial',
        'text_param_index': 'text',
        'return_audio_index': 0,
        'series': 'Fish Speech',
    },
    'mrfakename/E2-F5-TTS': {
        'name': 'F5 TTS',
        'function': '/predict',
        'text_param_index': 'gen_text',
        'return_audio_index': 0,
        'is_zero_gpu_space': True,
        'series': 'E2/F5 TTS',
        'title': 'Uses a voice sample from trained dataset',
    },
    'mrfakename/E2-F5-TTS/E2': {
        'name': 'E2 TTS',
        'function': '/basic_tts',
        'text_param_index': 'gen_text_input',
        'return_audio_index': 0,
        'is_zero_gpu_space': True,
        'series': 'E2/F5 TTS',
    },
    'Flux9665/MassivelyMultilingualTTS': {
        'name': 'IMS-Toucan',
        'function': '/predict',
        'text_param_index': 0,
        'return_audio_index': 0,
        'series': 'IMS-Toucan',
        'title': 'Changes voice pitch on each request',
    },
    'Flux9665/EnglishToucan': {
        'name': 'IMS-Toucan EN',
        'function': '/predict',
        'text_param_index': 0,
        'return_audio_index': 0,
        'series': 'IMS-Toucan',
        'emoji': '😒',
        'title': 'Narration voice',
    },
    'Pendrokar/style-tts-2': {
        'name': 'StyleTTS v2',
        'function': '/synthesize',
        'text_param_index': 'text',
        'return_audio_index': 0,
        'is_zero_gpu_space': True,
        'series': 'StyleTTS',
        'emoji': '😷',
        'title': 'Outclassed by Kokoro',
    },
    'hexgrad/kokoro': {
        'name': 'Kokoro v0.19',
        'function': '/generate',
        'text_param_index': 'text',
        'return_audio_index': 0,
        'is_zero_gpu_space': False,
        'series': 'Kokoro',
        'space_link': 'Remsky/Kokoro-TTS-Zero',
        'title': 'Deprecated: Kokoro v1.0+ improves pronunciation',
    },
    'hexgrad/Kokoro-TTS/0.23': {
        'name': 'StyleTTS Kokoro v23',
        'function': '/multilingual',
        'text_param_index': 'text',
        'return_audio_index': 0,
        'is_zero_gpu_space': True,
        'series': 'Kokoro',
        'title': 'Deprecated: Kokoro v1.0+ improves pronunciation',
    },
    'hexgrad/Kokoro-API': {
        'name': 'Kokoro v1.0',
        'function': '/predict',
        'text_param_index': 'text',
        'return_audio_index': 0,
        'is_zero_gpu_space': False,
        'series': 'Kokoro',
        'space_link': 'hexgrad/kokoro',
    },
    'amphion/maskgct': {
        'name': 'MaskGCT',
        'function': '/predict',
        'text_param_index': 1,
        'return_audio_index': 0,
        'is_zero_gpu_space': True,
        'series': 'MaskGCT',
        'emoji': '🥵',
        'title': 'Requires 300s reserved ZeroGPU time! Cannot afford!',
    },
    'Svngoku/maskgct-audio-lab': {
        'name': 'MaskGCT',
        'function': '/predict',
        'text_param_index': 1,
        'return_audio_index': 0,
        'is_zero_gpu_space': True,
        'series': 'MaskGCT',
        'emoji': '🥵',
        'title': 'Requires 300s reserved ZeroGPU time! Cannot afford!',
    },
    'lj1995/GPT-SoVITS-v2': {
        'name': 'GPT-SoVITS v2',
        'function': '/get_tts_wav',
        'text_param_index': 'text',
        'return_audio_index': 0,
        'is_zero_gpu_space': True,
        'series': 'GPT-SoVITS',
        'title': 'Outclassed',
    },
    'lj1995/GPT-SoVITS-ProPlus': {
        'name': 'GPT-SoVITS ProPlus',
        'function': '/get_tts_wav',
        'text_param_index': 'text',
        'return_audio_index': 0,
        'is_zero_gpu_space': True,
        'series': 'GPT-SoVITS',
        'title': 'Outclassed',
    },
    'ameerazam08/OuteTTS-0.2-500M-Demo': {
        'name': 'OuteTTS v0.2 500M',
        'function': '/generate_tts',
        'text_param_index': 0,
        'return_audio_index': 0,
        'is_zero_gpu_space': True,
        'series': 'OuteTTS',
        'emoji': '🥵',
        'title': 'Requires 300s reserved ZeroGPU time! Cannot afford!',
    },
    'OuteAI/OuteTTS-0.3-1B-Demo': {
        'name': 'OuteTTS v0.3 1B',
        'function': '/generate_tts',
        'text_param_index': 'text',
        'return_audio_index': 0,
        'is_zero_gpu_space': True,
        'series': 'OuteTTS',
        'emoji': '🥵',
        'title': 'Requires 300s reserved ZeroGPU time! Cannot afford!',
    },
    'HKUST-Audio/Llasa-1B-finetuned-for-two-speakers': {
        'name': 'LLaSA 1B',
        'function': '/predict',
        'text_param_index': 'input_text',
        'return_audio_index': 0,
        'is_zero_gpu_space': True,
        'series': 'LLaSA',
        'title': 'Broken space - Runtime error',
    },
    'srinivasbilla/llasa-3b-tts': {
        'name': 'LLaSA 3B',
        'function': '/infer',
        'text_param_index': 'target_text',
        'return_audio_index': 0,
        'is_zero_gpu_space': True,
        'series': 'LLaSA',
    },
    'srinivasbilla/llasa-8b-tts': {
        'name': 'LLaSA 8B',
        'function': '/infer',
        'text_param_index': 'target_text',
        'return_audio_index': 0,
        'is_zero_gpu_space': True,
        'series': 'LLaSA',
    },
    'CAMB-AI/mars5_space': {
        'name': 'MARS 5',
        'function': '/on_click',
        'text_param_index': 'text',
        'return_audio_index': 0,
        'is_zero_gpu_space': False,
        'series': 'MARS',
    },
    'CAMB-AI/mars6-turbo-demo': {
        'name': 'MARS 6',
        'function': '/inference',
        'text_param_index': 'text',
        'return_audio_index': 0,
        'is_zero_gpu_space': False,
        'is_closed_source': True,
        'series': 'MARS',
        'title': 'Unstable',
    },
    'Steveeeeeeen/Zonos': {
        'name': 'Zonos T',
        'function': '/generate_audio',
        'text_param_index': 'text',
        'return_audio_index': 0,
        'is_zero_gpu_space': True,
        'series': 'Zonos',
    },
    'Steveeeeeeen/Zonos/hybrid': {
        'name': 'Zonos H',
        'function': '/generate_audio',
        'text_param_index': 'text',
        'return_audio_index': 0,
        'is_zero_gpu_space': True,
        'series': 'Zonos',
        'title': 'Outclassed',
        'space_link': 'Steveeeeeeen/Zonos',
    },
    'thunnai/SparkTTS': {
        'name': 'Spark-TTS',
        'function': '/voice_clone',
        'text_param_index': 'text',
        'return_audio_index': 0,
        'is_zero_gpu_space': True,
        'series': 'Spark-TTS',
        'title': 'Outclassed',
    },
    'sesame/csm-1b': {
        'name': 'CSM 1B',
        'function': '/infer',
        'text_param_index': 'gen_conversation_input',
        'return_audio_index': 0,
        'is_zero_gpu_space': True,
        'series': 'CSM-1B',
        'title': 'Outclassed',
    },
    'MohamedRashad/Orpheus-TTS': {
        'name': 'Orpheus 3B v0.1',
        'function': '/generate_speech',
        'text_param_index': 'text',
        'return_audio_index': 0,
        'is_zero_gpu_space': True,
        'series': 'Orpheus',
    },
    'IndexTeam/IndexTTS': {
        'name': 'Index TTS',
        'function': '/gen_single',
        'text_param_index': 'text',
        'return_audio_index': 0,
        'is_zero_gpu_space': True,
        'series': 'Index',
        'title': 'Outclassed',
    },
    'nari-labs/Dia-1.6B': {
        'name': 'Dia',
        'function': '/generate_audio',
        'text_param_index': 'text_input',
        'return_audio_index': 0,
        'is_zero_gpu_space': True,
        'series': 'Dia',
        'title': 'Outclassed',
    },
    'ResembleAI/Chatterbox': {
        'name': 'Chatterbox',
        'function': '/generate_tts_audio',
        'text_param_index': 'text_input',
        'return_audio_index': 0,
        'is_zero_gpu_space': True,
        'series': 'Chatterbox',
    },
    'ByteDance/MegaTTS3': {
        'name': 'MegaTTS',
        'function': '/predict',
        'text_param_index': 'inp_text',
        'return_audio_index': 0,
        'is_zero_gpu_space': True,
        'series': 'MegaTTS',
    },
}

# Create files
output_dir = 'app/tts_spaces'
os.makedirs(output_dir, exist_ok=True)

for key, value in hf_spaces.items():
    # Create safe filename from key
    filename = key.replace('/', '__') + '.json'
    filepath = os.path.join(output_dir, filename)
    
    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump({key: key} ... value, f, indent=2, ensure_ascii=False)
    
    print(f"Created: {filepath}")

print(f"\nTotal files created: {len(hf_spaces)}")
